### 1. Initializing Time-MOE and Training ###

In [15]:
import pandas as pd
import numpy as np
import huggingface 
from time_moe.datasets.time_moe_dataset import TimeMoEDataset
from time_moe.datasets.time_moe_window_dataset import TimeMoEWindowDataset
import datetime
import os
import torch
import logging

for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)
    

# Configure logging
logging.basicConfig(    
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

print(f"CWD: {os.getcwd()}")


# # Set which GPU(s) are visible
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"   # Use only GPU 1

# # Check what GPUs PyTorch sees
# print(f'Number of GPUs Available: {torch.cuda.device_count()}')  # should show 1 if you set "1"
# print(f'Device 0 Name: {torch.cuda.get_device_name(0)}')  # the GPU PyTorch will use

CWD: c:\Users\yinki\OneDrive\NUS\BT4101\fyp-kiat\ML_Core\src

In [ ]:
# Loading of config
from utils.utils import load_config, config_to_args

config_file_path = '../config/config_tickers_448_7_Channels_with_temporal_tape_v2.yaml'
config_dict = load_config(config_file_path)

place_holders_to_replace = {'version_name': config_dict['regression']['common']['version_name']}
args = config_to_args(config_dict, place_holders_to_replace)

print(f"Current Version Name: {args.regression.common.version_name}")

Current Version Name: tickers_448_7_Channels_with_temporal_tape_v2

### Model Training Stage Time-MOE ###

In [3]:
# from time_moe.datasets import *
# from time_moe.runner import *
# from time_moe.trainer import *
# from time_moe.utils import *

# runner = TimeMoeRunner(
#         model_path=args.regression.Time_MOE.model_path,
#         output_path=args.regression.Time_MOE.output_path,
#         seed=args.regression.Time_MOE.train_seed,
#     )

# train_model_params_dict = args.regression.Time_MOE.train_model_args.__dict__
# train_model_params_dict['args'] = args
    
# model, _ = runner.train_model(
#     **train_model_params_dict
# )

### Time-MoE Hyperparameter Training and Retraining ###

In [4]:
from time_moe.datasets import *
from time_moe.runner import *
from time_moe.trainer import *
from time_moe.utils import *

runner = TimeMoeRunner(
        model_path=args.regression.Time_MOE.model_path,
        output_path=args.regression.Time_MOE.output_path,
        seed=args.regression.Time_MOE.train_seed,
    )

train_model_params_dict = args.regression.Time_MOE.train_model_args.__dict__
optuna_grid = args.regression.Time_MOE.optuna_grid
train_model_params_dict['args'] = args
train_model_params_dict['optuna_grid'] = optuna_grid.__dict__
    
model, best_params = runner.train_model(
    optuna_search=True,
    **train_model_params_dict,
)


# We then update and then do retraining
updated_model_config_update = {'model_configs': {}}
logging.info(f'Retraining on full training set')
for key, value in best_params.hyperparameters.items():
    if key in train_model_params_dict:
        logging.info(f'Updating {key} from {train_model_params_dict[key]} to {value}')
        train_model_params_dict[key] = value
    else:
        logging.info(f'Tracking Model Config Optimal Param for {key}: {value}')
        updated_model_config_update['model_configs'][key] = value

# Retraining with best hyperparameters
model, _ = runner.train_model(
    **train_model_params_dict,
    **updated_model_config_update
)

2025-10-27 17:19:19.637891: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-27 17:19:19.685359: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-27 17:19:20.944584: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-27 17:19:21 [INFO] PyTorch version 2.8.0 available.
2025-10-27 17:19:21 [INFO] TensorFlow version 2.20.0 available.

2025-10-27 17:19:21,687 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set global_batch_size to 128
2025-10-27 17:19:21,688 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set micro_batch_size to 16
2025-10-27 17:19:21,689 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set gradient_accumulation_steps to 8
2025-10-27 17:19:21,690 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set precision to fp32
2025-10-27 17:19:21,691 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set normalization to zero
2025-10-27 17:19:21,692 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Use Eager Attention

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2025-10-27 17:19:22,001 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn(

TimeMoeForPrediction(
  (model): TimeMoeModel(
    (embed_layer): MultiFreqInputEmbedding(
      (main_lstm): LSTM(1, 384, batch_first=True, dropout=0.1)
      (main_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (channel_lstms): ModuleList(
        (0): TimeEncodedLSTM(
          (input_proj): Linear(in_features=4, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (1): TimeEncodedLSTM(
          (input_proj): Linear(in_features=5, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (2-4): 3 x TimeEncodedLSTM(
          (input_proj): Linear(in_features=1, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (5): TimeEncodedLSTM(
          (input_proj): Linear(in_features=2, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
      )
      (channel_lns): ModuleList(
        (0-5): 6 x LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      )
      (query_proj): Linear(in_features=384, out_features=384, bias=True)
      (key_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (value_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=384, out_features=384, bias=True)
      )
      (output_proj): Linear(in_features=384, out_features=384, bias=True)
      (act_fn): GELU(approximate='none')
      (dropout): Dropout(p=0.3, inplace=False)
      (output_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList(
      (0-11): 12 x TimeMoeDecoderLayer(
        (self_attn): TimeMoeAttention(
          (q_proj): Linear(in_features=384, out_features=384, bias=True)
          (k_proj): Linear(in_features=384, out_features=384, bias=True)
          (v_proj): Linear(in_features=384, out_features=384, bias=True)
          (o_proj): Linear(in_features=384, out_features=384, bias=False)
          (rotary_emb): TimeMoeRotaryEmbedding()
        )
        (ffn_layer): TimeMoeSparseExpertsLayer(
          (gate): Linear(in_features=384, out_features=8, bias=False)
          (experts): ModuleList(
            (0-7): 8 x TimeMoeTemporalBlock(
              (gate_proj): Linear(in_features=384, out_features=768, bias=False)
              (up_proj): Linear(in_features=384, out_features=768, bias=False)
              (down_proj): Linear(in_features=768, out_features=384, bias=False)
              (act_fn): SiLU()
            )
          )
          (shared_expert): TimeMoeTemporalBlock(
            (gate_proj): Linear(in_features=384, out_features=1536, bias=False)
            (up_proj): Linear(in_features=384, out_features=1536, bias=False)
            (down_proj): Linear(in_features=1536, out_features=384, bias=False)
            (act_fn): SiLU()
          )
          (shared_expert_gate): Linear(in_features=384, out_features=1, bias=False)
        )
        (input_layernorm): TimeMoeRMSNorm()
        (post_attention_layernorm): TimeMoeRMSNorm()
      )
    )
    (norm): TimeMoeRMSNorm()
  )
  (lm_heads): ModuleList(
    (0): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=1, bias=False)
    )
    (1): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=8, bias=False)
    )
    (2): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=32, bias=False)
    )
    (3): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=64, bias=False)
    )
  )
  (loss_function): HuberLoss()
)
2025-10-27 17:19:23,177 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Load model parameters from: kiatkock/MV-Time-MOE
2025-10-27 17:19:23,181 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: TimeMoeConfig {
  "_name_or_path": "time_moe_50m",
  "apply_aux_loss": true,
  "architectures": [
    "TimeMoeForPrediction"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "Maple728/TimeMoE-50M--configuration_time_moe.TimeMoeConfig",
    "AutoModelForCausalLM": "Maple728/TimeMoE-50M--modeling_time_moe.TimeMoeForPrediction"
  },
  "channel_configs": [
    [
      63,
      1,
      1
    ],
    [
      6,
      1,
      4
    ],
    [
      6,
      1,
      5
    ],
    [
      10,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      2
    ]
  ],
  "embedding_hidden_size": 128,
  "hidden_act": "silu",
  "hidden_size": 384,
  "horizon_lengths": [
    1,
    8,
    32,
    64
  ],
  "initializer_range": 0.02,
  "input_size": 42,
  "intermediate_size": 1536,
  "max_position_embeddings": 4096,
  "model_type": "time_moe",
  "num_attention_heads": 12,
  "num_experts": 8,
  "num_experts_per_tok": 2,
  "num_hidden_layers": 12,
  "num_key_value_heads": 12,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000,
  "router_aux_loss_factor": 0.02,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_cache": true,
  "use_dense": false
}

2025-10-27 17:19:23,182 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Number of the model parameters: 130.813M
2025-10-27 17:19:23,183 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Initializaing Model Training with Optuna Search...
2025-10-27 17:19:23,184 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Loading dataset from disk... @ ../data/processed_data/feature_engineered_data_tickers_75_7_Channels_with_temporal_tape.parquet
2025-10-27 17:19:24,840 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Processing dataset to fixed-size sub-sequences....

2025-10-27 17:19:24 [INFO] MultiFrequencyTimeSeriesDatasetV2 initialized with Price context_length=63, prediction_length=8, window_size=63, stride=1, inferencing_mode=False
2025-10-27 17:19:24 [INFO] Resampling Dataset according to 1 rules
2025-10-27 17:19:24 [INFO] Resampling dataset, Current Dataset Length: 97200
2025-10-27 17:19:24 [INFO] Total windows available: 24300

2025-10-27 17:19:24,929 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Total Dataset Size: 24300....
2025-10-27 17:19:24,929 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Using cached dataset (avoiding disk I/O)
2025-10-27 17:19:26,555 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Processing dataset to fixed-size sub-sequences....

2025-10-27 17:19:26 [INFO] MultiFrequencyTimeSeriesDatasetV2 initialized with Price context_length=63, prediction_length=8, window_size=63, stride=1, inferencing_mode=False
2025-10-27 17:19:26 [INFO] Total windows available: 70725

2025-10-27 17:19:26,611 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Total Dataset Size: 70725....

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2025-10-27 17:19:26,964 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Loaded base config from kiatkock/MV-Time-MOE
2025-10-27 17:19:26,965 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: No Optuna trial — using base config only.
2025-10-27 17:19:26,966 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters:
2025-10-27 17:19:26,967 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters:
2025-10-27 17:19:26,970 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn(

TimeMoeForPrediction(
  (model): TimeMoeModel(
    (embed_layer): MultiFreqInputEmbedding(
      (main_lstm): LSTM(1, 384, batch_first=True, dropout=0.1)
      (main_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (channel_lstms): ModuleList(
        (0): TimeEncodedLSTM(
          (input_proj): Linear(in_features=4, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (1): TimeEncodedLSTM(
          (input_proj): Linear(in_features=5, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (2-4): 3 x TimeEncodedLSTM(
          (input_proj): Linear(in_features=1, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (5): TimeEncodedLSTM(
          (input_proj): Linear(in_features=2, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
      )
      (channel_lns): ModuleList(
        (0-5): 6 x LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      )
      (query_proj): Linear(in_features=384, out_features=384, bias=True)
      (key_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (value_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=384, out_features=384, bias=True)
      )
      (output_proj): Linear(in_features=384, out_features=384, bias=True)
      (act_fn): GELU(approximate='none')
      (dropout): Dropout(p=0.3, inplace=False)
      (output_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList(
      (0-11): 12 x TimeMoeDecoderLayer(
        (self_attn): TimeMoeAttention(
          (q_proj): Linear(in_features=384, out_features=384, bias=True)
          (k_proj): Linear(in_features=384, out_features=384, bias=True)
          (v_proj): Linear(in_features=384, out_features=384, bias=True)
          (o_proj): Linear(in_features=384, out_features=384, bias=False)
          (rotary_emb): TimeMoeRotaryEmbedding()
        )
        (ffn_layer): TimeMoeSparseExpertsLayer(
          (gate): Linear(in_features=384, out_features=8, bias=False)
          (experts): ModuleList(
            (0-7): 8 x TimeMoeTemporalBlock(
              (gate_proj): Linear(in_features=384, out_features=768, bias=False)
              (up_proj): Linear(in_features=384, out_features=768, bias=False)
              (down_proj): Linear(in_features=768, out_features=384, bias=False)
              (act_fn): SiLU()
            )
          )
          (shared_expert): TimeMoeTemporalBlock(
            (gate_proj): Linear(in_features=384, out_features=1536, bias=False)
            (up_proj): Linear(in_features=384, out_features=1536, bias=False)
            (down_proj): Linear(in_features=1536, out_features=384, bias=False)
            (act_fn): SiLU()
          )
          (shared_expert_gate): Linear(in_features=384, out_features=1, bias=False)
        )
        (input_layernorm): TimeMoeRMSNorm()
        (post_attention_layernorm): TimeMoeRMSNorm()
      )
    )
    (norm): TimeMoeRMSNorm()
  )
  (lm_heads): ModuleList(
    (0): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=1, bias=False)
    )
    (1): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=8, bias=False)
    )
    (2): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=32, bias=False)
    )
    (3): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=64, bias=False)
    )
  )
  (loss_function): HuberLoss()
)
TimeMoeConfig {
  "_name_or_path": "time_moe_50m",
  "apply_aux_loss": true,
  "architectures": [
    "TimeMoeForPrediction"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "Maple728/TimeMoE-50M--configuration_time_moe.TimeMoeConfig",
    "AutoModelForCausalLM": "Maple728/TimeMoE-50M--modeling_time_moe.TimeMoeForPrediction"
  },
  "channel_configs": [
    [
      63,
      1,
      1
    ],
    [
      6,
      1,
      4
    ],
    [
      6,
      1,
      5
    ],
    [
      10,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      2
    ]
  ],
  "embedding_hidden_size": 128,
  "hidden_act": "silu",
  "hidden_size": 384,
  "horizon_lengths": [
    1,
    8,
    32,
    64
  ],
  "initializer_range": 0.02,
  "input_size": 42,
  "intermediate_size": 1536,
  "max_position_embeddings": 4096,
  "model_type": "time_moe",
  "num_attention_heads": 12,
  "num_experts": 8,
  "num_experts_per_tok": 2,
  "num_hidden_layers": 12,
  "num_key_value_heads": 12,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000,
  "router_aux_loss_factor": 0.02,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_cache": true,
  "use_dense": false
}

2025-10-27 17:19:28,703 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Initializing Model Training with Optuna Search...

[I 2025-10-27 17:19:28,752] A new study created in memory with name: no-name-e65b2bce-92b9-4174-be16-b27727cd3db5

2025-10-27 17:19:28,999 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Loaded base config from kiatkock/MV-Time-MOE
2025-10-27 17:19:29,002 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters:
2025-10-27 17:19:29,003 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters: hidden_size=528, num_hidden_layers=16, num_attention_heads=12, num_experts=12, hidden_dropout=0.04827350647673254, attention_dropout=0.09709428509127932, hidden_act=relu
2025-10-27 17:19:29,006 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]
TimeMoeForPrediction(
  (model): TimeMoeModel(
    (embed_layer): MultiFreqInputEmbedding(
      (main_lstm): LSTM(1, 528, batch_first=True, dropout=0.1)
      (main_ln): LayerNorm((528,), eps=1e-05, elementwise_affine=True)
      (channel_lstms): ModuleList(
        (0): TimeEncodedLSTM(
          (input_proj): Linear(in_features=4, out_features=528, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(528, 528, num_layers=2, batch_first=True, dropout=0.1)
        )
        (1): TimeEncodedLSTM(
          (input_proj): Linear(in_features=5, out_features=528, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(528, 528, num_layers=2, batch_first=True, dropout=0.1)
        )
        (2-4): 3 x TimeEncodedLSTM(
          (input_proj): Linear(in_features=1, out_features=528, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(528, 528, num_layers=2, batch_first=True, dropout=0.1)
        )
        (5): TimeEncodedLSTM(
          (input_proj): Linear(in_features=2, out_features=528, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(528, 528, num_layers=2, batch_first=True, dropout=0.1)
        )
      )
      (channel_lns): ModuleList(
        (0-5): 6 x LayerNorm((528,), eps=1e-05, elementwise_affine=True)
      )
      (query_proj): Linear(in_features=528, out_features=528, bias=True)
      (key_proj): ModuleList(
        (0-5): 6 x Linear(in_features=528, out_features=528, bias=True)
      )
      (value_proj): ModuleList(
        (0-5): 6 x Linear(in_features=528, out_features=528, bias=True)
      )
      (attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=528, out_features=528, bias=True)
      )
      (output_proj): Linear(in_features=528, out_features=528, bias=True)
      (act_fn): GELU(approximate='none')
      (dropout): Dropout(p=0.3, inplace=False)
      (output_ln): LayerNorm((528,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList(
      (0-15): 16 x TimeMoeDecoderLayer(
        (self_attn): TimeMoeAttention(
          (q_proj): Linear(in_features=528, out_features=528, bias=True)
          (k_proj): Linear(in_features=528, out_features=528, bias=True)
          (v_proj): Linear(in_features=528, out_features=528, bias=True)
          (o_proj): Linear(in_features=528, out_features=528, bias=False)
          (rotary_emb): TimeMoeRotaryEmbedding()
        )
        (ffn_layer): TimeMoeSparseExpertsLayer(
          (gate): Linear(in_features=528, out_features=12, bias=False)
          (experts): ModuleList(
            (0-11): 12 x TimeMoeTemporalBlock(
              (gate_proj): Linear(in_features=528, out_features=768, bias=False)
              (up_proj): Linear(in_features=528, out_features=768, bias=False)
              (down_proj): Linear(in_features=768, out_features=528, bias=False)
              (act_fn): ReLU()
            )
          )
          (shared_expert): TimeMoeTemporalBlock(
            (gate_proj): Linear(in_features=528, out_features=1536, bias=False)
            (up_proj): Linear(in_features=528, out_features=1536, bias=False)
            (down_proj): Linear(in_features=1536, out_features=528, bias=False)
            (act_fn): ReLU()
          )
          (shared_expert_gate): Linear(in_features=528, out_features=1, bias=False)
        )
        (input_layernorm): TimeMoeRMSNorm()
        (post_attention_layernorm): TimeMoeRMSNorm()
      )
    )
    (norm): TimeMoeRMSNorm()
  )
  (lm_heads): ModuleList(
    (0): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=528, out_features=1, bias=False)
    )
    (1): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=528, out_features=8, bias=False)
    )
    (2): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=528, out_features=32, bias=False)
    )
    (3): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=528, out_features=64, bias=False)
    )
  )
  (loss_function): HuberLoss()
)
TimeMoeConfig {
  "_name_or_path": "time_moe_50m",
  "apply_aux_loss": true,
  "architectures": [
    "TimeMoeForPrediction"
  ],
  "attention_dropout": 0.09709428509127932,
  "auto_map": {
    "AutoConfig": "Maple728/TimeMoE-50M--configuration_time_moe.TimeMoeConfig",
    "AutoModelForCausalLM": "Maple728/TimeMoE-50M--modeling_time_moe.TimeMoeForPrediction"
  },
  "channel_configs": [
    [
      63,
      1,
      1
    ],
    [
      6,
      1,
      4
    ],
    [
      6,
      1,
      5
    ],
    [
      10,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      2
    ]
  ],
  "embedding_hidden_size": 128,
  "hidden_act": "relu",
  "hidden_dropout": 0.04827350647673254,
  "hidden_size": 528,
  "horizon_lengths": [
    1,
    8,
    32,
    64
  ],
  "initializer_range": 0.02,
  "input_size": 42,
  "intermediate_size": 1536,
  "max_position_embeddings": 4096,
  "model_type": "time_moe",
  "num_attention_heads": 12,
  "num_experts": 12,
  "num_experts_per_tok": 2,
  "num_hidden_layers": 16,
  "num_key_value_heads": 12,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000,
  "router_aux_loss_factor": 0.02,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_cache": true,
  "use_dense": false
}

W1027 17:19:40.677000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [3/8] torch._dynamo hit config.recompile_limit (8)
W1027 17:19:40.677000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [3/8]    function: '_check_and_fix_nans' (/home/yinkiat/fyp-kiat/ML_Core/src/time_moe/models/modeling_time_moe.py:453)
W1027 17:19:40.677000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [3/8]    last reason: 3/7: tensor 'tensor' requires_grad mismatch. expected requires_grad=1
W1027 17:19:40.677000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [3/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1027 17:19:40.677000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [3/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
W1027 17:19:59.354000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [13/8] torch._dynamo hit config.recompile_limit (8)
W1027 17:19:59.354000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [13/8]    function: 'forward' (/home/yinkiat/fyp-kiat/ML_Core/src/time_moe/models/modeling_time_moe.py:1126)
W1027 17:19:59.354000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [13/8]    last reason: 13/7: len(past_key_value.key_cache) == 7
W1027 17:19:59.354000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [13/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1027 17:19:59.354000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [13/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.

[I 2025-10-27 17:38:30,821] Trial 0 finished with value: 0.36959511041641235 and parameters: {'learning_rate': 0.00011170884489439903, 'weight_decay': 0.10278280150977431, 'adam_beta1': 0.9194078403096464, 'adam_beta2': 0.9693981307125369, 'num_train_epochs': 2, 'warmup_steps': 411, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'optim': 'adamw_torch', 'model_hidden_size': 528, 'model_num_hidden_layers': 16, 'model_num_attention_heads': 12, 'model_num_experts': 12, 'model_hidden_dropout': 0.04827350647673254, 'model_attention_dropout': 0.09709428509127932, 'model_hidden_act': 'relu'}. Best is trial 0 with value: 0.36959511041641235.
/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2025-10-27 17:38:32,181 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Loaded base config from kiatkock/MV-Time-MOE
2025-10-27 17:38:32,184 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters:
2025-10-27 17:38:32,186 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Final model config hyperparameters: hidden_size=288, num_hidden_layers=12, num_attention_heads=12, num_experts=8, hidden_dropout=0.17313589950069397, attention_dropout=0.19461903552392804, hidden_act=gelu
2025-10-27 17:38:32,188 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn(

TimeMoeForPrediction(
  (model): TimeMoeModel(
    (embed_layer): MultiFreqInputEmbedding(
      (main_lstm): LSTM(1, 288, batch_first=True, dropout=0.1)
      (main_ln): LayerNorm((288,), eps=1e-05, elementwise_affine=True)
      (channel_lstms): ModuleList(
        (0): TimeEncodedLSTM(
          (input_proj): Linear(in_features=4, out_features=288, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(288, 288, num_layers=2, batch_first=True, dropout=0.1)
        )
        (1): TimeEncodedLSTM(
          (input_proj): Linear(in_features=5, out_features=288, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(288, 288, num_layers=2, batch_first=True, dropout=0.1)
        )
        (2-4): 3 x TimeEncodedLSTM(
          (input_proj): Linear(in_features=1, out_features=288, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(288, 288, num_layers=2, batch_first=True, dropout=0.1)
        )
        (5): TimeEncodedLSTM(
          (input_proj): Linear(in_features=2, out_features=288, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(288, 288, num_layers=2, batch_first=True, dropout=0.1)
        )
      )
      (channel_lns): ModuleList(
        (0-5): 6 x LayerNorm((288,), eps=1e-05, elementwise_affine=True)
      )
      (query_proj): Linear(in_features=288, out_features=288, bias=True)
      (key_proj): ModuleList(
        (0-5): 6 x Linear(in_features=288, out_features=288, bias=True)
      )
      (value_proj): ModuleList(
        (0-5): 6 x Linear(in_features=288, out_features=288, bias=True)
      )
      (attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=288, out_features=288, bias=True)
      )
      (output_proj): Linear(in_features=288, out_features=288, bias=True)
      (act_fn): GELU(approximate='none')
      (dropout): Dropout(p=0.3, inplace=False)
      (output_ln): LayerNorm((288,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList(
      (0-11): 12 x TimeMoeDecoderLayer(
        (self_attn): TimeMoeAttention(
          (q_proj): Linear(in_features=288, out_features=288, bias=True)
          (k_proj): Linear(in_features=288, out_features=288, bias=True)
          (v_proj): Linear(in_features=288, out_features=288, bias=True)
          (o_proj): Linear(in_features=288, out_features=288, bias=False)
          (rotary_emb): TimeMoeRotaryEmbedding()
        )
        (ffn_layer): TimeMoeSparseExpertsLayer(
          (gate): Linear(in_features=288, out_features=8, bias=False)
          (experts): ModuleList(
            (0-7): 8 x TimeMoeTemporalBlock(
              (gate_proj): Linear(in_features=288, out_features=768, bias=False)
              (up_proj): Linear(in_features=288, out_features=768, bias=False)
              (down_proj): Linear(in_features=768, out_features=288, bias=False)
              (act_fn): GELUActivation()
            )
          )
          (shared_expert): TimeMoeTemporalBlock(
            (gate_proj): Linear(in_features=288, out_features=1536, bias=False)
            (up_proj): Linear(in_features=288, out_features=1536, bias=False)
            (down_proj): Linear(in_features=1536, out_features=288, bias=False)
            (act_fn): GELUActivation()
          )
          (shared_expert_gate): Linear(in_features=288, out_features=1, bias=False)
        )
        (input_layernorm): TimeMoeRMSNorm()
        (post_attention_layernorm): TimeMoeRMSNorm()
      )
    )
    (norm): TimeMoeRMSNorm()
  )
  (lm_heads): ModuleList(
    (0): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=288, out_features=1, bias=False)
    )
    (1): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=288, out_features=8, bias=False)
    )
    (2): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=288, out_features=32, bias=False)
    )
    (3): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=288, out_features=64, bias=False)
    )
  )
  (loss_function): HuberLoss()
)
TimeMoeConfig {
  "_name_or_path": "time_moe_50m",
  "apply_aux_loss": true,
  "architectures": [
    "TimeMoeForPrediction"
  ],
  "attention_dropout": 0.19461903552392804,
  "auto_map": {
    "AutoConfig": "Maple728/TimeMoE-50M--configuration_time_moe.TimeMoeConfig",
    "AutoModelForCausalLM": "Maple728/TimeMoE-50M--modeling_time_moe.TimeMoeForPrediction"
  },
  "channel_configs": [
    [
      63,
      1,
      1
    ],
    [
      6,
      1,
      4
    ],
    [
      6,
      1,
      5
    ],
    [
      10,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      2
    ]
  ],
  "embedding_hidden_size": 128,
  "hidden_act": "gelu",
  "hidden_dropout": 0.17313589950069397,
  "hidden_size": 288,
  "horizon_lengths": [
    1,
    8,
    32,
    64
  ],
  "initializer_range": 0.02,
  "input_size": 42,
  "intermediate_size": 1536,
  "max_position_embeddings": 4096,
  "model_type": "time_moe",
  "num_attention_heads": 12,
  "num_experts": 8,
  "num_experts_per_tok": 2,
  "num_hidden_layers": 12,
  "num_key_value_heads": 12,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000,
  "router_aux_loss_factor": 0.02,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_cache": true,
  "use_dense": false
}

W1027 17:38:34.317000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [7/8] torch._dynamo hit config.recompile_limit (8)
W1027 17:38:34.317000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [7/8]    function: 'forward' (/home/yinkiat/fyp-kiat/ML_Core/src/time_moe/models/modeling_time_moe.py:327)
W1027 17:38:34.317000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [7/8]    last reason: 7/7: tensor 'x' size mismatch at index 2. expected 2, actual 4
W1027 17:38:34.317000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [7/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1027 17:38:34.317000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [7/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
W1027 17:38:36.012000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [21/8] torch._dynamo hit config.recompile_limit (8)
W1027 17:38:36.012000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [21/8]    function: 'forward' (/home/yinkiat/fyp-kiat/ML_Core/src/time_moe/models/modeling_time_moe.py:1405)
W1027 17:38:36.012000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [21/8]    last reason: 21/7: tensor 'self._modules['out_layer']._parameters['weight']' size mismatch at index 0. expected 64, actual 1. Guard failed on a parameter, consider using torch._dynamo.config.force_parameter_static_shapes = False to allow dynamism on parameters.
W1027 17:38:36.012000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [21/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W1027 17:38:36.012000 1134898 /home/yinkiat/.pyenv/versions/3.12.6/envs/time-moe-env/lib/python3.12/site-packages/torch/_dynamo/convert_frame.py:1016] [21/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.

[I 2025-10-27 17:50:18,781] Trial 1 finished with value: 0.3531273603439331 and parameters: {'learning_rate': 0.00042175180680300894, 'weight_decay': 0.019529775672752218, 'adam_beta1': 0.9037050239740964, 'adam_beta2': 0.9675889344224324, 'num_train_epochs': 2, 'warmup_steps': 21, 'per_device_train_batch_size': 16, 'lr_scheduler_type': 'cosine', 'optim': 'adamw_torch_fused', 'model_hidden_size': 288, 'model_num_hidden_layers': 12, 'model_num_attention_heads': 12, 'model_num_experts': 8, 'model_hidden_dropout': 0.17313589950069397, 'model_attention_dropout': 0.19461903552392804, 'model_hidden_act': 'gelu'}. Best is trial 1 with value: 0.3531273603439331.

2025-10-27 17:50:18,783 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO:
============================================================
2025-10-27 17:50:18,784 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Hyperparameter Search Complete!
2025-10-27 17:50:18,784 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: ============================================================
2025-10-27 17:50:18,785 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Best run ID: 1
2025-10-27 17:50:18,786 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Best objective (eval_loss): 0.3531
2025-10-27 17:50:18,787 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO:
Best hyperparameters:
2025-10-27 17:50:18,787 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: learning_rate: 0.00042175180680300894
2025-10-27 17:50:18,788 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: weight_decay: 0.019529775672752218
2025-10-27 17:50:18,789 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: adam_beta1: 0.9037050239740964
2025-10-27 17:50:18,789 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: adam_beta2: 0.9675889344224324
2025-10-27 17:50:18,790 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: num_train_epochs: 2
2025-10-27 17:50:18,791 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: warmup_steps: 21
2025-10-27 17:50:18,792 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: per_device_train_batch_size: 16
2025-10-27 17:50:18,792 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: lr_scheduler_type: cosine
2025-10-27 17:50:18,793 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: optim: adamw_torch_fused
2025-10-27 17:50:18,794 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_hidden_size: 288
2025-10-27 17:50:18,795 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_num_hidden_layers: 12
2025-10-27 17:50:18,795 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_num_attention_heads: 12
2025-10-27 17:50:18,796 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_num_experts: 8
2025-10-27 17:50:18,797 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_hidden_dropout: 0.17313589950069397
2025-10-27 17:50:18,798 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_attention_dropout: 0.19461903552392804
2025-10-27 17:50:18,798 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: model_hidden_act: gelu
2025-10-27 17:50:18,802 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Saved best hyperparameters to ../data/outputs/tickers_75_7_Channels_with_temporal_tape_optuna_best_hyperparams.json

2025-10-27 17:50:18 [INFO] Retraining on full training set
2025-10-27 17:50:18 [INFO] Updating learning_rate from 0.0001 to 0.00042175180680300894
2025-10-27 17:50:18 [INFO] Updating weight_decay from 0.1 to 0.019529775672752218
2025-10-27 17:50:18 [INFO] Updating adam_beta1 from 0.9 to 0.9037050239740964
2025-10-27 17:50:18 [INFO] Updating adam_beta2 from 0.95 to 0.9675889344224324
2025-10-27 17:50:18 [INFO] Updating num_train_epochs from 2.0 to 2
2025-10-27 17:50:18 [INFO] Updating warmup_steps from 0 to 21
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for per_device_train_batch_size: 16
2025-10-27 17:50:18 [INFO] Updating lr_scheduler_type from cosine to cosine
2025-10-27 17:50:18 [INFO] Updating optim from adamw_torch_fused to adamw_torch_fused
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_hidden_size: 288
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_num_hidden_layers: 12
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_num_attention_heads: 12
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_num_experts: 8
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_hidden_dropout: 0.17313589950069397
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_attention_dropout: 0.19461903552392804
2025-10-27 17:50:18 [INFO] Tracking Model Config Optimal Param for model_hidden_act: gelu

2025-10-27 17:50:18,816 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set global_batch_size to 128
2025-10-27 17:50:18,817 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set micro_batch_size to 16
2025-10-27 17:50:18,817 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set gradient_accumulation_steps to 8
2025-10-27 17:50:18,818 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set precision to fp32
2025-10-27 17:50:18,818 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Set normalization to zero
2025-10-27 17:50:18,819 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Use Eager Attention

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2025-10-27 17:50:19,113 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]

/home/yinkiat/.pyenv/versions/time-moe-env/lib/python3.12/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn(

TimeMoeForPrediction(
  (model): TimeMoeModel(
    (embed_layer): MultiFreqInputEmbedding(
      (main_lstm): LSTM(1, 384, batch_first=True, dropout=0.1)
      (main_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      (channel_lstms): ModuleList(
        (0): TimeEncodedLSTM(
          (input_proj): Linear(in_features=4, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (1): TimeEncodedLSTM(
          (input_proj): Linear(in_features=5, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (2-4): 3 x TimeEncodedLSTM(
          (input_proj): Linear(in_features=1, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
        (5): TimeEncodedLSTM(
          (input_proj): Linear(in_features=2, out_features=384, bias=True)
          (tape): TemporalAwaretAPE(
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (lstm): LSTM(384, 384, num_layers=2, batch_first=True, dropout=0.1)
        )
      )
      (channel_lns): ModuleList(
        (0-5): 6 x LayerNorm((384,), eps=1e-05, elementwise_affine=True)
      )
      (query_proj): Linear(in_features=384, out_features=384, bias=True)
      (key_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (value_proj): ModuleList(
        (0-5): 6 x Linear(in_features=384, out_features=384, bias=True)
      )
      (attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=384, out_features=384, bias=True)
      )
      (output_proj): Linear(in_features=384, out_features=384, bias=True)
      (act_fn): GELU(approximate='none')
      (dropout): Dropout(p=0.3, inplace=False)
      (output_ln): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
    )
    (layers): ModuleList(
      (0-11): 12 x TimeMoeDecoderLayer(
        (self_attn): TimeMoeAttention(
          (q_proj): Linear(in_features=384, out_features=384, bias=True)
          (k_proj): Linear(in_features=384, out_features=384, bias=True)
          (v_proj): Linear(in_features=384, out_features=384, bias=True)
          (o_proj): Linear(in_features=384, out_features=384, bias=False)
          (rotary_emb): TimeMoeRotaryEmbedding()
        )
        (ffn_layer): TimeMoeSparseExpertsLayer(
          (gate): Linear(in_features=384, out_features=8, bias=False)
          (experts): ModuleList(
            (0-7): 8 x TimeMoeTemporalBlock(
              (gate_proj): Linear(in_features=384, out_features=768, bias=False)
              (up_proj): Linear(in_features=384, out_features=768, bias=False)
              (down_proj): Linear(in_features=768, out_features=384, bias=False)
              (act_fn): SiLU()
            )
          )
          (shared_expert): TimeMoeTemporalBlock(
            (gate_proj): Linear(in_features=384, out_features=1536, bias=False)
            (up_proj): Linear(in_features=384, out_features=1536, bias=False)
            (down_proj): Linear(in_features=1536, out_features=384, bias=False)
            (act_fn): SiLU()
          )
          (shared_expert_gate): Linear(in_features=384, out_features=1, bias=False)
        )
        (input_layernorm): TimeMoeRMSNorm()
        (post_attention_layernorm): TimeMoeRMSNorm()
      )
    )
    (norm): TimeMoeRMSNorm()
  )
  (lm_heads): ModuleList(
    (0): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=1, bias=False)
    )
    (1): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=8, bias=False)
    )
    (2): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=32, bias=False)
    )
    (3): TimeMoeOutputLayerSingular(
      (out_layer): Linear(in_features=384, out_features=64, bias=False)
    )
  )
  (loss_function): HuberLoss()
)
2025-10-27 17:50:20,368 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Load model parameters from: kiatkock/MV-Time-MOE
2025-10-27 17:50:20,372 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: TimeMoeConfig {
  "_name_or_path": "time_moe_50m",
  "apply_aux_loss": true,
  "architectures": [
    "TimeMoeForPrediction"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "Maple728/TimeMoE-50M--configuration_time_moe.TimeMoeConfig",
    "AutoModelForCausalLM": "Maple728/TimeMoE-50M--modeling_time_moe.TimeMoeForPrediction"
  },
  "channel_configs": [
    [
      63,
      1,
      1
    ],
    [
      6,
      1,
      4
    ],
    [
      6,
      1,
      5
    ],
    [
      10,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      1
    ],
    [
      5,
      1,
      2
    ]
  ],
  "embedding_hidden_size": 128,
  "hidden_act": "silu",
  "hidden_size": 384,
  "horizon_lengths": [
    1,
    8,
    32,
    64
  ],
  "initializer_range": 0.02,
  "input_size": 42,
  "intermediate_size": 1536,
  "max_position_embeddings": 4096,
  "model_type": "time_moe",
  "num_attention_heads": 12,
  "num_experts": 8,
  "num_experts_per_tok": 2,
  "num_hidden_layers": 12,
  "num_key_value_heads": 12,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000,
  "router_aux_loss_factor": 0.02,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_cache": true,
  "use_dense": false
}

2025-10-27 17:50:20,373 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Number of the model parameters: 130.813M
2025-10-27 17:50:20,377 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Using cached dataset (avoiding disk I/O)
2025-10-27 17:50:21,791 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Processing dataset to fixed-size sub-sequences....

2025-10-27 17:50:21 [INFO] MultiFrequencyTimeSeriesDatasetV2 initialized with Price context_length=63, prediction_length=8, window_size=63, stride=1, inferencing_mode=False
2025-10-27 17:50:21 [INFO] Resampling Dataset according to 1 rules
2025-10-27 17:50:21 [INFO] Resampling dataset, Current Dataset Length: 97200
2025-10-27 17:50:21 [INFO] Total windows available: 24300

2025-10-27 17:50:21,844 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Total Dataset Size: 24300....
2025-10-27 17:50:21,844 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Using cached dataset (avoiding disk I/O)
2025-10-27 17:50:23,194 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Processing dataset to fixed-size sub-sequences....

2025-10-27 17:50:23 [INFO] MultiFrequencyTimeSeriesDatasetV2 initialized with Price context_length=63, prediction_length=8, window_size=63, stride=1, inferencing_mode=False
2025-10-27 17:50:23 [INFO] Total windows available: 70725

2025-10-27 17:50:23,229 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Total Dataset Size: 70725....
2025-10-27 17:50:23,230 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: Initializaing Model Training full without Optuna Search...
2025-10-27 17:50:23,231 - log_util.py[pid:1134898;line:52:log_in_local_rank_0] - INFO: TimeMoETrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'gradient_accumulation_kwargs': None},
adafactor=False,
adam_beta1=0.9037050239740964,
adam_beta2=0.9675889344224324,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=3003,
dataloader_drop_last=False,
dataloader_num_workers=4,
dataloader_persistent_workers=True,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=False,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_steps=250,
evaluation_strategy=IntervalStrategy.STEPS,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=8,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.00042175180680300894,
length_column_name=length,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=False,
logging_dir=/home/yinkiat/logs/time_moe_tickers_75_7_Channels_with_temporal_tape/tb_logs,
logging_first_step=True,
logging_nan_inf_filter=True,
logging_steps=50,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
min_learning_rate=5e-05,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=2.0,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=/home/yinkiat/logs/time_moe_tickers_75_7_Channels_with_temporal_tape,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=16,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=/home/yinkiat/logs/time_moe_tickers_75_7_Channels_with_temporal_tape,
save_on_each_node=False,
save_only_model=True,
save_safetensors=True,
save_steps=250,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=1,
seed=3003,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=True,
torch_compile_backend=inductor,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=21,
weight_decay=0.019529775672752218,
)

KeyboardInterrupt:

### TensorBoard Visualisation ###

In [ ]:
### Tensorboard Visualisaiong
import tensorflow as tf
import pandas as pd
from pathlib import Path
import os

# Path to your events file
event_file = Path(f"{args.regression.Time_MOE.output_path}/tb_logs")
logging.info(f"Searching for TB Logs @ {event_file}")
latest_event = [i for i in os.listdir(event_file) if i.startswith('events.out.tfevents')][-1]
logging.info(f"Found TensorBoard Event File {latest_event}")
file_path = os.path.join(event_file, latest_event)

# for f in os.listdir(event_file):
#     if f.startswith('events.out.tfevents'):
#         file_path = os.path.join(event_file, f)
#         logging.info(f"Found TensorBoard Event File {f}")
#         break
        
# Lists to store results
steps = []
tags = []
values = []

# Iterate through the event file
for e in tf.compat.v1.train.summary_iterator(str(file_path)):
    for v in e.summary.value:
        steps.append(e.step)
        tags.append(v.tag)
        values.append(v.simple_value)

# Convert to DataFrame for easy analysis
df = pd.DataFrame({
    "step": steps,
    "tag": tags,
    "value": values
}).drop_duplicates()

# Assume df is your DataFrame
df_filtered = df[df['step'] != 0]  # ignore step 0

# Pivot with aggregation to handle duplicates
df_pivot = df_filtered.pivot_table(
    index='step',
    columns='tag',
    values='value',
    aggfunc='first'  # take the first occurrence if duplicates exist
).reset_index()

df_pivot

In [ ]:
# Plotting of Tensorboard logs in 2x2 subplots
import matplotlib.pyplot as plt

metrics = ['train/loss', 'train/grad_norm', 'train/learning_rate', 'eval/loss']

fig, axes = plt.subplots(2, 2, figsize=(12, 8))  # 2x2 layout
axes = axes.flatten()  # flatten into 1D array for easy looping

for i, m in enumerate(metrics):
    ax = axes[i]
    df_pivot_metrics = df_pivot[['step', m]].dropna()
    ax.plot(df_pivot_metrics['step'], df_pivot_metrics[m], label=m)
    ax.set_title(f'{m}', fontsize=14)
    ax.set_xlabel('Step', fontsize=12)
    ax.set_ylabel('Value', fontsize=12)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.legend(fontsize=10)
    ax.tick_params(axis='both', labelsize=10)

plt.tight_layout()
plt.show()

#### Pushing to HuggingFace to save Tensor Weights, Optional ####

In [ ]:
from huggingface_hub import HfApi
from datetime import datetime, timezone, timedelta

# Define Singapore timezone (UTC+8)
sgt = timezone(timedelta(hours=8))
datetime_str = datetime.now(sgt).strftime("%Y-%m-%d %H:%M:%S")

# Initialize API
api = HfApi(token=args.regression.Time_MOE.train_model_args.hub_token)

# Upload folder to Hugging Face Hub
api.upload_folder(
    folder_path=args.regression.Time_MOE.output_path,
    repo_id=args.regression.Time_MOE.model_path,
    repo_type="model",
    commit_message=f"{args.regression.common.version_name} model training @ {datetime_str}"
)

### Model Inferencing Stage Time-MoE ###

In [17]:
from S3_Model_Training import S3_model_inferencing_multi_frequency


# Model Inferencing Code
all_sequences_inf = S3_model_inferencing_multi_frequency(args, None, None)

2026-01-23 20:41:35 [INFO] Inititating Model Inferencing....................
2026-01-23 20:41:35 [INFO] Model set as None! Loading from HuggingFace @ kiatkock/MV-Time-MOE
c:\Users\yinki\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

2026-01-23 20:41:36,574 - log_util.py[pid:12120;line:52:log_in_local_rank_0] - INFO: Channel Configs Inputted: [[63, 1, 1], [6, 1, 4], [6, 1, 5], [10, 1, 1], [5, 1, 1], [5, 1, 1], [5, 1, 2]]

c:\Users\yinki\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn(
2026-01-23 20:43:13 [INFO] MultiFrequencyTimeSeriesDatasetV2 initialized with Price context_length=63, prediction_length=8, window_size=63, stride=1, inferencing_mode=True
2026-01-23 20:43:13 [INFO] Total windows available: 80460
2026-01-23 20:43:13 [INFO] Created DataLoader with 80460 samples, batch_size=8, shuffle=True, num_workers=0
100%|██████████| 10058/10058 [2:09:27<00:00,  1.29it/s]
2026-01-23 22:52:41 [INFO] Model Inferencing Completed!
2026-01-23 22:52:41 [INFO] Saving the individual inferenced sequences
2026-01-23 22:53:24 [INFO] Saved the individual inferenced sequences to ../data/outputs/tickers_448_7_Channels_with_temporal_tape_v2_all_inference_sequences.pkl